apiVersion: v1
kind: PersistentVolume
metadata:
  name: course-learning-postgres-volume
  labels:
    type: local
    app: course-learning-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/course-learning-postgresql
