apiVersion: v1
kind: ConfigMap
metadata:
  name: course-learning-postgres-secret
  labels:
    app: course-learning-postgres
data:
  POSTGRES_DB: course_learning_ps_db
  POSTGRES_USER: course_learning_ps_user
  POSTGRES_PASSWORD: CourseLearningSecurePassword
