apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-postgres
  template:
    metadata:
      labels:
        app: admin-postgres
    spec:
      containers:
        - name: admin-postgres
          image: 'postgres:17'
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '768Mi'
              cpu: '750m'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: admin-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: admin-postgresdata
      volumes:
        - name: admin-postgresdata
          persistentVolumeClaim:
            claimName: admin-postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: admin-postgres-srv
spec:
  selector:
    app: admin-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
