apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-postgres-volume
  labels:
    type: local
    app: admin-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/admin-postgresql-fresh
