apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-postgres-secret
  labels:
    app: admin-postgres
data:
  POSTGRES_DB: admin_ps_db
  POSTGRES_USER: admin_ps_user
  POSTGRES_PASSWORD: AdminSecurePassword
