apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-problem-postgres-volume
  labels:
    type: local
    app: code-problem-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/code-problem-postgresql-fresh
