apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      containers:
        - name: cm
          image: questify/cm
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cm-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URI
              value: 'postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@cm-postgres-srv:5432/$(POSTGRES_DB)'
---
apiVersion: v1
kind: Service
metadata:
  name: cm-srv
spec:
  selector:
    app: cm
  ports:
    - name: cm
      protocol: TCP
      port: 3000
      targetPort: 3000
