apiVersion: v1
kind: ConfigMap
metadata:
  name: course-mgmt-postgres-secret
  labels:
    app: course-mgmt-postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
