apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-mgmt-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-mgmt
  template:
    metadata:
      labels:
        app: course-mgmt
    spec:
      containers:
        - name: course-mgmt
          image: questify/course-mgmt
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: course-mgmt-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: course-mgmt-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: course-mgmt-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URI
              value: 'postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@course-mgmt-postgres-srv:5432/$(POSTGRES_DB)'
---
apiVersion: v1
kind: Service
metadata:
  name: course-mgmt-srv
spec:
  selector:
    app: course-mgmt
  ports:
    - name: course-mgmt
      protocol: TCP
      port: 3000
      targetPort: 3000
