name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save questify
      - run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      - run: kubectl apply -f infra/k8s-persistent -R
